spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    database: h2
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: demo
    password:


management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: '*'

springdoc:
  show-actuator: true